apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: acme.com/guestbook:zzzzzz
        resources:
          limits:
            memory: 128Mi
            cpu: "0.7"
          requests:
            memory: 64Mi
            cpu: "0.2"
